# Generated by Django 4.2.13 on 2024-06-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='acces_token',
            new_name='access_token',
        ),
    ]
